# F:\my-docker-microservices\inventory-database\Dockerfile
FROM postgres:14-alpine
# We rely on environment variables for POSTGRES_USER and POSTGRES_PASSWORD
# so no manual creation of user/password here.

EXPOSE 5432
CMD ["postgres"]